appointment:
  handler: src/appointment/infrastructure/controller/AppointmentCloudController.handler
  events:
    - http:
        path: appointments
        method: post
        summary: "Crear una cita médica"
        description: "Endpoint para programar una cita médica"
        swaggerTags: ["Appointments"]
        bodyType: "AppointmentRequest"
        responseData:
          201:
            description: "Cita creada con éxito"
            bodyType: "AppointmentResponse"
          400:
            description: "Los Datos de entrada no son validos"
          500:
            description: "Error interno del servidor"
        operationId: "createAppointment"
    - http:
        path: appointments/{insuredId}
        method: get
        summary: "Consultar citas por código del asegurado"
        description: "Consultar todas las citas de un asegurado"
        swaggerTags: ["Appointments"]
        responseData:
          200:
            description: "Lista de citas"
            bodyType: "AppointmentListResponse"
          404:
            description: "Asegurado no cuenta con citas"
          500:
            description: "Error interno del servidor"
        operationId: "getAppointmentsByInsuredId"
    - sqs:
          arn:
            Fn::GetAtt: [AppointmentQueueSqsCompleted, Arn]
          batchSize: 1
        
appointment_pe:
  handler: src/appointment/infrastructure/controller/AppointmentCoreController.main
  events:
    - sqs:
        arn:
          Fn::GetAtt: [AppointmentQueuePESqs, Arn]
        batchSize: 5
  environment:
    DB_HOST: ${env:DB_HOST_PE}
    DB_USERNAME: ${env:DB_USER_PE}
    DB_PASSWORD: ${env:DB_PASSWORD_PE}
    DB_NAME: ${env:DB_NAME_PE}
    DB_PORT: ${env:DB_PORT_PE}

appointment_cl:
  handler: src/appointment/infrastructure/controller/AppointmentCoreController.main
  events:
    - sqs:
        arn:
          Fn::GetAtt: [AppointmentQueueCLSqs, Arn]
        batchSize: 5
  environment:
    DB_HOST: ${env:DB_HOST_CL}
    DB_USERNAME: ${env:DB_USER_CL}
    DB_PASSWORD: ${env:DB_PASSWORD_CL}
    DB_NAME: ${env:DB_NAME_CL}
    DB_PORT: ${env:DB_PORT_CL}